version: '3.1'

services:

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
        - 5432:5432

  togo-app:
    image: .
    restart: always
    environment:
      DB_HOST: database
      DB_USER: postgre
      DB_PASS: postgre
      DATABASE: postgre
    ports:
      - 8080:8080
      

